import json
import os
import random
from datetime import datetime



TOPICS = {
    "Agentic AI": [
        "Autonomous AI agents use reasoning, planning, memory, and tool utilization to complete complex multi-step tasks with minimal human intervention.",
        "Modern agentic systems are powered by large language models that can interact with APIs, databases, search engines, and external software tools.",
        "Multi-agent architectures enable collaborative problem solving where specialized AI agents coordinate to accomplish complex objectives efficiently.",
        "Agentic AI systems are increasingly used in workflow automation, research assistance, software engineering,and enterprise decision support platforms."
    ],

    "Transformers": [
        "Transformer architectures transformed modern natural language processing by replacing recurrent neural networks with self-attention mechanisms that capture long-range contextual dependencies between tokens.",
        "Large language models such as GPT and BERT rely heavily on transformer layers for contextual reasoning, semantic understanding, and next-token prediction tasks across massive text corpora.",
        "Transformers are widely used in semantic retrieval systems, question answering pipelines, conversational AI assistants, and multimodal foundation models.",
        "Attention mechanisms allow transformer networks to focus on relevant parts of an input sequence, significantly improving translation, summarization, and retrieval tasks."
    ],

    "Semantic Search": [
        "Semantic retrieval systems understand contextual meaning instead of relying solely on exact keyword matching across documents and queries.",
        "Embedding models convert textual information into dense vector representations that capture semantic similarity between phrases, documents, and concepts.",
        "Hybrid retrieval combines BM25 lexical search with vector similarity search to improve ranking quality and recall.",
        "Modern semantic search systems are widely used in enterprise knowledge management, AI assistants, recommendation systems, and question-answering applications."
    ],

    "Machine Learning": [
        "Machine learning algorithms learn patterns from historical data to make predictions, classifications, and automated decisions across diverse applications.",
        "Supervised learning models are trained using labeled datasets to solve tasks such as fraud detection, image classification,and customer behavior prediction.",
        "Neural networks can model highly nonlinear relationships and have become fundamental components of deep learning systems for computer vision and NLP.",
        "Model evaluation metrics such as precision, recall, F1-score, and ROC-AUC are critical for assessing predictive performance and generalization quality."
    ],

    "Cloud Computing": [
        "Cloud computing platforms provide scalable infrastructure for deploying distributed applications, databases, AI systems, and enterprise services globally.",
        "Kubernetes orchestrates containerized workloads by automating deployment, scaling, monitoring, and resource allocation across clusters.",
        "Docker containers package applications and dependencies into portable runtime environments that simplify deployment and continuous integration pipelines.",
        "Cloud-native architectures improve system resilience, fault tolerance, scalability, and operational efficiency for modern software platforms."
    ],

    "Vector Databases": [
        "Vector databases store high-dimensional embedding vectors generated by machine learning models for semantic retrieval and similarity search tasks.",
        "Approximate nearest neighbor search algorithms significantly improve retrieval latency while maintaining acceptable similarity search accuracy.",
        "FAISS enables efficient indexing and retrieval over massive embedding collections used in recommendation engines and AI-powered search systems.",
        "Modern retrieval systems use vector indexing to support semantic search, conversational AI, recommendation systems, and retrieval-augmented generation pipelines."
    ],

    "RAG Systems": [
        "Retrieval-Augmented Generation combines document retrieval with generative language models to improve factual accuracy and contextual grounding.",
        "RAG pipelines retrieve relevant information from vector databases before generating responses using large language models.",
        "Document chunking strategies improve retrieval granularity by splitting large documents into semantically meaningful sections.",
        "Hybrid retrieval architectures enhance response quality by combining lexical search signals with semantic vector-based retrieval techniques."
    ],

    "FastAPI": [
        "FastAPI is a modern Python web framework designed for building high-performance APIs with automatic validation and OpenAPI documentation support.",
        "Pydantic models validate request and response schemas, ensuring strong type safety and structured API contracts across services.",
        "Asynchronous API endpoints improve scalability by enabling concurrent request handling for I/O-intensive workloads such as database queries and vector retrieval.",
        "FastAPI is widely used for machine learning inference APIs, AI microservices, backend orchestration systems, and real-time analytics platforms."
    ],

    "Cybersecurity": [
    """
Intrusion detection systems monitor network traffic to identify
malicious behavior and unauthorized access attempts.
""",

    """
Security information and event management platforms aggregate
logs from distributed systems for threat analysis.
""",

    """
Modern cybersecurity systems increasingly use AI models for
threat intelligence and anomaly detection.
"""
],

    "Financial Technology": [
    """
Algorithmic trading systems use real-time market data and
predictive analytics to execute automated trading strategies.
""",

    """
Fraud detection systems analyze transactional anomalies using
machine learning classification algorithms.
""",

    """
Risk assessment models help financial institutions evaluate
creditworthiness and investment exposure.
"""
],
    "Healthcare AI": [
    """
Deep learning models assist radiologists in detecting tumors,
fractures, and abnormalities from medical imaging scans such
as MRIs and CT images.
""",

    """
AI-powered diagnostic systems improve clinical decision making
by analyzing patient records, lab reports, and historical
treatment outcomes.
""",

    """
Healthcare analytics platforms use machine learning models to
predict disease progression and optimize hospital resource
allocation.
"""
],
    
}

random.seed(42)

def generate_document(doc_id, topic):
    related_topics = random.sample(list(TOPICS.keys()), 4)

    paragraphs = []

    paragraphs.extend(random.sample(TOPICS[topic], 3))

    for related in related_topics:
        if related != topic:
            paragraphs.append(random.choice(TOPICS[related]))

    text = " ".join(paragraphs)

    return {
        "doc_id": str(doc_id),
        "title": f"{topic} Article {doc_id}",
        "text": text,
        "source": "synthetic",
        "created_at": datetime.utcnow().isoformat()
    }


def main():
    os.makedirs("data/processed", exist_ok=True)

    output_path = "data/processed/docs.jsonl"

    documents = []

    for i in range(1, 301):
        topic = random.choice(list(TOPICS.keys()))
        doc = generate_document(i, topic)
        documents.append(doc)

    with open(output_path, "w", encoding="utf-8") as f:
        for doc in documents:
            f.write(json.dumps(doc) + "\n")

    print(f"Generated {len(documents)} realistic documents")


if __name__ == "__main__":
    main()
